---
title: "New York State Public Schools: Graduation Rates"
output: 
 flexdashboard::flex_dashboard:
   orientation: rows
   source_code: embed
   vertical_layout: scroll
   horizontal_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(reshape2)
library(shiny)
library(Hmisc)
```

```{r global, include=FALSE}
#Prepare the dataset
# Read and examine fields of dataset
df_NY_schools <- read.csv(file = "GRAD_RATE_AND_OUTCOMES_2018.csv")

df_NY_schools[, c(20:36)] <- sapply(df_NY_schools[, c(20:36)], as.character)

# Change the string columns with the percent symbols to numeric percentages
to_percent <- function(orig_text) {
  without_symbol <- substr(orig_text,1, nchar(orig_text)-1)
  to_number <- as.numeric(without_symbol)
  to_percent <- to_number / 100
  return(to_percent)
}

new_pct <- sapply(df_NY_schools[, c("GRAD_PCT", "REG_PCT", "STILL_ENR_PCT", "GED_PCT",
                                    "DROPOUT_PCT", "LOCAL_PCT", "REG_ADV_PCT",
                                    "NON_DIPLOMA_CREDENTIAL_PCT")], to_percent)

df_NY_schools_withoutpct <- df_NY_schools %>% 
  select(-c("GRAD_PCT", "REG_PCT", "STILL_ENR_PCT", "GED_PCT",
            "DROPOUT_PCT", "LOCAL_PCT", "REG_ADV_PCT",
            "NON_DIPLOMA_CREDENTIAL_PCT"))

df_NY_schools_corrected <- cbind(df_NY_schools_withoutpct, new_pct)

# Now convert the counts to numeric
df_NY_schools_corrected[, c(20:28)] <- sapply(df_NY_schools_corrected[, c(20:28)], as.numeric)

# Check to see if the number of reported dropouts makes sense
df_NY_schools_corrected$dropout_check <- df_NY_schools_corrected$ENROLL_CNT - 
  df_NY_schools_corrected$GRAD_CNT -
  df_NY_schools_corrected$STILL_ENR_CNT

# Remove unnecessary columns and add year
df_NY_schools_corrected <- df_NY_schools_corrected %>% 
  select(-LEA_BEDS, -LEA_NAME, -NRC_DESC,
         -NYC_IND, -BOCES_CODE, -MEMBERSHIP_CODE, -MEMBERSHIP_KEY) %>% 
    mutate(Year = substr(MEMBERSHIP_DESC, 1, 4))

# Subset by statewide so have statewide reference for individual counties
# Remove one of the 4 year outcomes of the 2014 cohort (there is a june & august value)
# Choose August as it is more recent
df_state <- subset(df_NY_schools_corrected,
                   subset = AGGREGATION_TYPE == 'Statewide' &
                     MEMBERSHIP_DESC != '2014 Total Cohort - 4 Year Outcome')

# Subset data to a single aggregation index. In this case, we will choose county
df_county <- subset(x = df_NY_schools_corrected,
                    subset = AGGREGATION_TYPE == "County" &
                      MEMBERSHIP_DESC != '2014 Total Cohort - 4 Year Outcome') %>% 
  arrange(COUNTY_NAME)

# Create dataset of county-level appended to state-level
df_county_state <- rbind(df_county, df_state)

# Create list of counties
df_county$COUNTY_NAME <- as.character(df_county$COUNTY_NAME)

```


Inputs {.sidebar}
=====================================
```{r}
# Select a county
selectInput(inputId = "county", "Select a county:",
            choices = unique(df_county$COUNTY_NAME))

br()

# Select cohort year
radioButtons(inputId = "cohortYear", "Select a cohort year:",
              choices = unique(df_county_state$Year), selected = '2014')
helpText("A cohort is the group of students who entered 9th grade in the chosen year.")


br()
# Select student demographic group
selectInput(inputId = "demoGroup", label = "Select a student demographic  group:", 
                   choices = c("Gender" = "Gen", "Ethnicity" = "Eth", "Economic 
                               Status" = "Eco", 
                               "English Language Learner" = "ELL"),
                   selected = "Eth")
    
```


General County-level Metrics
=====================================  

Row 
-------------------------------------

### Student Enrollment
```{r fig.height=8}

# Value box for number of all students in the county per cohort
county_students <- reactive({
  df_county %>% 
    filter(COUNTY_NAME == input$county & Year == input$cohortYear) %>% 
    filter(SUBGROUP_NAME == "All Students")
})

renderValueBox({
  enrolled_students <- format(county_students()$ENROLL_CNT, big.mark = ",") 
  valueBox(caption = "Total Number of Enrolled Students 
           (All Demographic Groups)", value = enrolled_students,
           icon = "fa-user-graduate")
})

```

### Graduation Rate
```{r fig.height=12}
renderGauge({
  grad_pct <-100*county_students()$GRAD_PCT
  gauge(grad_pct, min = 0, max = 100, symbol = '%', 
      gaugeSectors(success = c(90, 100), warning = c(75, 89), danger = c(0, 74)
      ))
})

```

Row
-------------------------------------

### County vs. State Metrics Comparison
```{r}
# Data aggregated for all students
all_stud <- df_county_state %>% 
  filter(SUBGROUP_NAME == "All Students") %>% 
  arrange(desc(DROPOUT_CNT))

all_stud_long <- melt(all_stud,
                      id.vars = c("AGGREGATION_TYPE", "AGGREGATION_NAME", 
                                  "COUNTY_NAME", "AGGREGATION_CODE", "Year"))

# Subset by variables of interest for bar chart
all_stud_long_bar <- all_stud_long %>% 
  filter(variable %in% c('GRAD_PCT', 'DROPOUT_PCT', 'STILL_ENR_PCT', 'GED_PCT'))

all_stud_long_bar$value = sapply(all_stud_long_bar$value, as.numeric)

# Dataset for county and cohort year
selected_county <- reactive({
  all_stud_long_bar %>%  
    filter(Year == input$cohortYear) %>% 
    filter(AGGREGATION_NAME == "All Districts and Charters" | 
             COUNTY_NAME == input$county) 
  })

# Bar chart displaying graduation, dropout, still enrolled, and GED prep program rates by county as compared to NY state averages

theme1 <- theme(legend.title = element_blank(),
          legend.text = element_text(size=14),
          axis.title = element_text(size=14),
          axis.text = element_text(size=14),
          plot.title = element_text(size=14))

renderPlot({
  ggplot(selected_county()) +
    geom_bar(stat = "identity",
             aes(x = variable, y = value, fill = AGGREGATION_NAME),
             position = "dodge") +
    xlab("") +
    ylab('Rate') + 
    theme1 +
    scale_y_continuous(breaks=seq(0,1,.10)) +
    scale_fill_brewer(palette = "Set1")
  })

```

Row
-------------------------------------
```{r}
br()
p("1) Graduated: students who received a diploma; 2) Dropped out: students whose last enrollment record indicates they dropped out; 3) GED: students whose last enrollment record indicates they transferred to a high school equivalency program; 4) Still enrolled: students whose last enrollment record indicates they are still enrolled")
```

Student Demographics
=====================================  

Row
-------------------------------------

### Demographic Makeup
```{r fig.height=8}

dem_melt <- melt(df_county, id.vars = c("SUBGROUP_CODE", "SUBGROUP_NAME",
                                       "COUNTY_NAME", "Year")) %>% 
  filter(variable %in% c("GRAD_PCT", "DROPOUT_PCT")) 
dem_melt$value <- as.numeric(dem_melt$value)

# Citation for the following method: https://stackoverflow.com/questions/37710358/how-to-create-if-statement-with-reactive-values-in-r-shiny?rq=1

# Select the subgroup codes for the given demographic input
state <- reactiveValues()
observeEvent(input$demoGroup, {
  if(input$demoGroup == "Gen") {
    state$a = c(2,3)
    state$b = c(2) # female code
    state$c = "female"} 
  if(input$demoGroup == "Eth") {
    state$a = c(4,5,6,7,8,9)
    state$b = c(4,5,6,7,9) # non-white code
    state$c = "non-white"}   
  if(input$demoGroup == "Eco") {
    state$a = c(15,16)
    state$b = c(15)  # eco disadvantaged code
    state$c = "economically disadvantaged"}
  if(input$demoGroup == "ELL") {
    state$a = c(12,13,14) 
    state$b = c(13,14) # not ELL code
    state$c = "former or current English language learners"} 
})

group_students <- reactive({
  df_county %>% 
  filter(SUBGROUP_CODE %in% state$b) %>% 
  filter(COUNTY_NAME == input$county & Year == input$cohortYear) %>% 
  select(ENROLL_CNT)
})

renderValueBox({
  group_pct <- round(100*(sum(na.omit(group_students()$ENROLL_CNT))/county_students()$ENROLL_CNT), 0)
  valueBox(caption = paste("Students who are", state$c),
           value = paste0(group_pct, "%"),
           icon = "fa-child")
})
```

Row
-------------------------------------
### Metrics by Demographic Group
```{r}
# Filter by selected county, year, and demographic group
selected_dem <- reactive({
  dem_melt %>% 
    filter(SUBGROUP_CODE %in% state$a) %>% 
    filter(COUNTY_NAME == input$county & Year == input$cohortYear)
})
# Bar chart displaying metrics by demographic group
renderPlot({
ggplot(data = selected_dem()) +
  geom_bar(stat = "identity",
           aes(x = variable, y = value, fill = SUBGROUP_NAME),
           position = "dodge") +
    xlab("") +
    ylab('Rate') +
  theme1 +
  scale_y_continuous(breaks=seq(0,1,.10)) +
    scale_fill_brewer(palette = "Set1")
})

```

Row
-------------------------------------
### Datatable
```{r fig.height=12}
# All data for a given county
county_data <- reactive({
  df_county %>% 
    filter(COUNTY_NAME == input$county) %>% 
    select(c(1,3,5,8,10,12,13:29))
})

DT::renderDataTable(
    DT::datatable(data = county_data(),
                  options = list(scrollY="100vh"))
  )
```


Metrics by Cohort
=====================================  

### 2012, 2013, and 2014 Cohort Performance
```{r}
p("According to the NY State Education Department website, a cohort is defined as \"a group of students who first entered grade 9 in the same school year.\" For example, the 2012 cohort is the group of students who entered grade 9 in the year 2012.")
br()

# Dataset for metrics of 2012/2013/2014 cohorts
cohort_melted <- melt(all_stud, id.vars = c("COUNTY_NAME", "Year")) %>% 
  filter(variable %in% c("GRAD_PCT", "DROPOUT_PCT", "STILL_ENR_PCT"))
cohort_melted$value <- as.numeric(cohort_melted$value)

cohort_county <- reactive({
  cohort_melted %>%
    filter(COUNTY_NAME == input$county)
})

# Scatterplot of metrics by cohort
renderPlot({
  ggplot(cohort_county()) +
    geom_point(aes(x = Year, y = value, color = variable), size = 7) +
    ylab("Rate") +
    xlab("Year") +
    ggtitle(paste(input$cohortYear, "Cohort in", capitalize(tolower(input$county)), "County")) +
    theme1 +
    scale_y_continuous(breaks=seq(0,1,.10)) +
    scale_color_brewer(palette = "Set1")
}, width = 800, height = 400
)
  
```


